# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio of Patrick M. D. Barbour
email: barbour@pmdbar.com
description: > # this means to ignore newlines until "baseurl:"
  This site describes my work in web development since Jan 1 2018.
  I specialize in artist websites, music websites and educational online apps.
  Thank you for looking and please do not hesitate to contact me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pmdbar
github_username:  pmdbar

# Build settings
markdown: kramdown
