# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design Portfolio | Patrick M. D. Barbour
email: barbour@pmdbar.com
description: > # this means to ignore newlines until "baseurl:"
  Compilation of Patrick M.D. Barbour's professional projects since Jan 1 2018.
  Website Projects: art, business, educational.
  Design Projects: 3-D modeling, brand development.
  Coding Projects: JavaScript, Python, React.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.yourdomain.com" # the base hostname & protocol for your site
twitter_username: pmdbar
github_username:  pmdbar

# Build settings
markdown: kramdown
